apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-preview-application
spec:
  description: >-
    Deploys a preview version of a service for isolated integration testing. Based on tekton-catalog kuberenetes-actions
    task. Expects a Kustomize application in the source subdirctory "preview". Makes a copy of the preview manifests
    replacing any instance of ${IMAGE_TAG} with the value passed for the parameter image-version.
  params:
    - name: project-name
      description: The project name for the application to install (should match GitHub repo and Docker image name)
      type: string
    - name: namespace
      description: The namespace to install the preview into
      type: string
    - name: git-revision
      description: The current git-revision, used to access the preview Helm chart
      type: string
    - name: image-version
      description: Version of the Docker image to deploy
      type: string
    - name: kubectl-image
      default: gcr.io/cloud-builders/kubectl@sha256:8ab94be8b2b4f3d117f02d868b39540fddd225447abf4014f7ba4765cb39f753 #image is huge
      description: Kubectl wrapper image
  workspaces:
    - name: source
  steps:
    - name: deploy-preview-application
      workingDir: $(workspaces.source.path)
      image: $(params.kubectl-image)
      script: |
        #!/usr/bin/env bash
        set -xe

        export IMAGE_TAG=$(params.image-version)
        cp -r preview preview-parsed
        for file in `find preview-parsed -type f`
        do 
          sed -i "s/\${IMAGE_TAG}/${IMAGE_TAG}/g" $file
        done

        kubectl apply -n $(params.namespace) -k preview-parsed

        kubectl wait -n $(params.namespace) --for=condition=Ready ksvc/$(params.project-name)
