apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.baseName }}-k8ssandra-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: k8ssandra-operator
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    repoURL: https://github.com/k8ssandra/k8ssandra-operator/
    path: config/deployments/control-plane
    targetRevision: v1.3.0
  syncPolicy:
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
