---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-sa
  namespace: greenlight-pipelines
secrets:
  - name: docker-registry-credentials
  - name: git-auth

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pipeline-role
rules:
  - apiGroups: ["extensions", "apps", ""]
    resources: ["services", "deployments", "pods", "configmaps"]
    verbs: ["get", "create", "update", "patch", "list", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pipeline-role
subjects:
  - kind: ServiceAccount
    name: pipeline-sa
    namespace: greenlight-pipelines

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pipeline-cluster-role
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "create", "update", "patch", "list", "delete"]
  - apiGroups: ["argoproj.io"]
    resources: ["applications"]
    verbs: ["get", "create", "update", "patch", "list", "delete"]
  - apiGroups: ["networking.istio.io"]
    resources: ["virtualservices"]
    verbs: ["get", "create", "update", "patch", "list", "delete", "watch"]
  - apiGroups: ["serving.knative.dev"]
    resources: ["services"]
    verbs: ["get", "create", "update", "patch", "list", "delete", "watch"]
  - apiGroups: ["serving.knative.dev"]
    resources: ["configurations"]
    verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pipeline-cluster-role-binding
roleRef:
  kind: ClusterRole
  name: pipeline-cluster-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: pipeline-sa
    namespace: greenlight-pipelines