apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-triggers-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-triggers-clusteradmin-eventlistener-binding
subjects:
- kind: ServiceAccount
  name: tekton-triggers-admin
  namespace: greenlight-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-triggers-clusteradmin-eventlistener-clusterbinding
subjects:
- kind: ServiceAccount
  name: tekton-triggers-admin
  namespace: greenlight-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles