apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: verdaccio
    app.kubernetes.io/instance: greenlight-verdaccio
    app.kubernetes.io/name: verdaccio
  name: verdaccio
  namespace: greenlight-pipelines
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: verdaccio
      app.kubernetes.io/name: verdaccio
  strategy:
    rollingUpdate: null
    type: Recreate
  template:
    metadata:
      labels:
        app: verdaccio
        app.kubernetes.io/instance: verdaccio
        app.kubernetes.io/name: verdaccio
    spec:
      containers:
        - env:
            - name: GITHUBTOKEN
              valueFrom:
                secretKeyRef:
                  key: botGithubTokenValue
                  name: bot-github-token
            - name: VERDACCIO_PORT
              value: "4873"
          image: 'verdaccio/verdaccio:5.13.3'
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /-/ping
              port: http
            initialDelaySeconds: 5
          name: verdaccio
          ports:
            - containerPort: 4873
              name: http
          readinessProbe:
            httpGet:
              path: /-/ping
              port: http
            initialDelaySeconds: 5
          securityContext:
            runAsUser: 10001
          volumeMounts:
            - mountPath: /verdaccio/storage
              name: storage
              readOnly: false
            - mountPath: /verdaccio/storage/htpasswd
              name: htpasswd
              subPath: htpasswd
              readOnly: true
            - mountPath: /verdaccio/conf
              name: config
              readOnly: true
      securityContext:
        fsGroup: 101
      serviceAccountName: default
      volumes:
        - name: config
          configMap:
            name: verdaccio
        - name: htpasswd
          secret:
            secretName: verdaccio-htpasswd
        - name: storage
          persistentVolumeClaim:
            claimName: verdaccio