apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: deploy-stage-pipeline-event-listener
  namespace: greenlight-pipelines
spec:
  serviceAccountName: tekton-triggers-admin
  triggers:
    - name: deploy-stage-pipeline-trigger
      template:
        ref: deploy-stage-pipeline-trigger-template
      bindings:
        - kind: TriggerBinding
          ref: push-trigger-binding
      interceptors:
        - name: GitHub push
          ref:
            name: github
          params:
            - name: secretRef
              value:
                secretName: webhook-secret
                secretKey: webhookSecretValue
            - name: eventTypes
              value: ["push"]
        - name: "CEL filter: main branch pushed"
          ref:
            name: cel
          params:
            - name: filter
              value: "body.ref == 'refs/heads/main' || body.ref == 'refs/heads/master'"
            - name: overlays
              value:
                - key: build_type
                  expression: "'service'"
                - key: branch_name
                  expression: "body.ref.split('/')[2]"
                - key: hub_organization
                  expression: "body.organization.login.replace('-', '')"
