apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: pull-request-trigger-binding
  namespace: greenlight-pipelines
spec:
  params:
    - name: project-name
      value: $(body.repository.name)
    - name: repository-full-name
      value: $(body.repository.full_name)
    - name: git-revision
      value: $(body.pull_request.head.sha)
    - name: git-branch
      value: $(body.pull_request.head.ref)
    - name: git-base-branch
      value: $(body.pull_request.base.ref)
    - name: git-pr-action
      value: $(body.action)
    - name: git-pr-number
      value: $(body.number)
    - name: git-pr-commit-number
      value: $(body.pull_request.commits)
    - name: preview-namespace
      value: prvw-$(extensions.short_repository_identifier)-pr-$(body.number)
    - name: build-type
      value: $(extensions.build_type)
    - name: hub-organization
      value: $(extensions.hub_organization)
