apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: service-pipeline-event-listener
  namespace: greenlight-pipelines
spec:
  serviceAccountName: tekton-triggers-admin
  triggers:
    - name: pr-pipeline-trigger
      template:
        ref: pr-pipeline-trigger-template
      bindings:
        - kind: TriggerBinding
          ref: pull-request-trigger-binding
      interceptors:
        - github:
            secretRef:
              secretName: webhook-secret
              secretKey: webhookSecretValue
            eventTypes:
              - pull_request
        - cel:
            filter: "body.action in ['opened', 'reopened', 'synchronize']"
            overlays:
              - key: build_type
                expression: "'service'"
              - key: hub_organization
                expression: "body.owner.login.replace('-', '')"
    - name: close-pr-pipeline-trigger
      template:
        ref: close-pr-pipeline-trigger-template
      bindings:
        - kind: TriggerBinding
          ref: pull-request-trigger-binding
      interceptors:
        - github:
            secretRef:
              secretName: webhook-secret
              secretKey: webhookSecretValue
            eventTypes:
              - pull_request
        - cel:
            filter: "body.action in ['closed']"
            overlays:
              - key: build_type
                expression: "'service'"
              - key: hub_organization
                expression: "body.owner.login.replace('-', '')"
    - name: main-pipeline-trigger
      template:
        ref: main-pipeline-trigger-template
      bindings:
        - kind: TriggerBinding
          ref: push-trigger-binding
      interceptors:
        - github:
            secretRef:
              secretName: webhook-secret
              secretKey: webhookSecretValue
            eventTypes:
              - push
        - cel:
            filter: "body.ref == 'refs/heads/main' || body.ref == 'refs/heads/master'"
            overlays:
              - key: build_type
                expression: "'service'"
              - key: branch_name
                expression: "body.ref.split('/')[2]"
              - key: hub_organization
                expression: "body.organization.login.replace('-', '')"
