apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: test-stage-close-pr-pipeline-trigger-template
spec:
  params:
    - name: project-name
      description: The repo name in GitHub, also used as the name for the Kaniko image
    - name: repository-full-name
      description: The repo name in GitHub qualified by the user/organization (e.g. greenlight-coop/helloworld)
    - name: git-revision
      description: The revision to clone and build
    - name: git-pr-number
      description: GitHub pull request number
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: $(tt.params.project-name)-close-pr-pipeline-run-
        namespace: greenlight-pipelines
      spec:
        pipelineRef:
          name: test-stage-close-pr-pipeline
        podTemplate:
          securityContext:
            runAsUser: 0
        serviceAccountName: pipeline-sa
        params:
          - name: project-name
            value: $(tt.params.project-name)
          - name: repository-full-name
            value: $(tt.params.repository-full-name)
          - name: git-revision
            value: $(tt.params.git-revision)  
          - name: git-pr-number
            value: $(tt.params.git-pr-number)  
        workspaces:
          - name: git-source
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
          - name: status-workspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Ki
                storageClassName: rook-nfs-share1
          - name: kubeconfig-dir
            emptyDir: {}
          - name: manifest-dir
            emptyDir: {}