apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: test-stage-pipeline-event-listener
  namespace: greenlight-pipelines
spec:
  serviceAccountName: tekton-triggers-admin
  triggers:
    - name: test-stage-pr-pipeline-trigger
      template:
        ref: test-stage-pr-pipeline-trigger-template
      bindings:
        - kind: TriggerBinding
          ref: pull-request-trigger-binding
      interceptors:
        - name: GitHub pull request
          ref:
            name: github
          params:
            - name: secretRef
              value:
                secretName: webhook-secret
                secretKey: webhookSecretValue
            - name: eventTypes
              value: ["pull_request"]
        - name: "CEL filter: PR opened, reopened or synchronized"
          ref:
            name: cel
          params:
            - name: filter
              value: "body.action in ['opened', 'reopened', 'synchronize']"
            - name: overlays
              value:
                - key: build_type
                  expression: "'test'"
                - key: hub_organization
                  expression: "body.organization.login.replace('-', '')"
    - name: test-stage-close-pr-pipeline-trigger
      template:
        ref: test-stage-close-pr-pipeline-trigger-template
      bindings:
        - kind: TriggerBinding
          ref: pull-request-trigger-binding
      interceptors:
        - name: GitHub pull request
          ref:
            name: github
          params:
            - name: secretRef
              value:
                secretName: webhook-secret
                secretKey: webhookSecretValue
            - name: eventTypes
              value: ["pull_request"]
        - name: "CEL filter: PR closed"
          ref:
            name: cel
          params:
            - name: filter
              value: "body.action in ['closed']"
            - name: overlays
              value:
                - key: build_type
                  expression: "'test'"
                - key: hub_organization
                  expression: "body.organization.login.replace('-', '')"

