---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: node-pipeline-trigger-template
spec:
  params:
    - name: project-name
      description: The repo name in GitHub, also used as the name for the Kaniko image
    - name: git-revision
      description: The revision to clone and build
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: $(tt.params.project-name)-build-pipeline-run-
        namespace: greenlight-pipelines
      spec:
        pipelineRef:
          name: node-build-pipeline
        serviceAccountName: pipeline-sa
        params:
          - name: project-name
            value: $(tt.params.project-name)
          - name: git-revision
            value: $(tt.params.git-revision)  
        workspaces:
          - name: git-source
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
          - name: project-info
            configMap:
              name: greenlight-projects
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: node-pipeline-trigger-binding
  namespace: greenlight-pipelines
spec:
  params:
    - name: project-name
      value: $(body.repository.name)
    - name: git-revision
      value: $(body.pull_request.head.ref)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: node-pipeline-event-listener
  namespace: greenlight-pipelines
spec:
  serviceAccountName: tekton-triggers-admin
  triggers:
    - name: node-pipeline-trigger
      template:
        ref: node-pipeline-trigger-template
      bindings:
        - ref: node-pipeline-trigger-binding
      interceptors:
        - github:
            eventTypes:
              - pull_request

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.global.tlsCertIssuer }}
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  name: node-pipeline-trigger-ingress
  namespace: greenlight-pipelines
spec:
  rules:
    - host: tekton.{{ .Values.global.appsDomainName }}
      http:
        paths:
          - backend:
              serviceName: el-node-pipeline-event-listener
              servicePort: 8080
            path: /webhook/node-pipeline
  tls:
    - hosts:
        - tekton.{{ .Values.global.appsDomainName }}
      secretName: {{ .Values.global.tlsCertIssuer }}
