---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: github-trigger-template
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: helloworld-build-pipeline-run
        namespace: greenlight-pipelines
      spec:
        pipelineRef:
          name: node-build-pipeline
        serviceAccountName: pipeline-sa
        params:
          - name: project-name
            value: helloworld
          - name: git-revision
            value: HEAD  
        workspaces:
          - name: git-source
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:gc
  name: github-event-listener
  namespace: greenlight-pipelines
spec:
  serviceAccountName: tekton-triggers-admin
  triggers:
    - name: github-trigger
      template:
        ref: github-trigger-template
      interceptors:
        - github:
            eventTypes:
              - pull_request

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.global.tlsCertIssuer }}
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  name: github-trigger-ingress
  namespace: greenlight-pipelines
spec:
  rules:
    - host: tekton.{{ .Values.global.appsDomainName }}
      http:
        paths:
          - backend:
              serviceName: el-github-event-listener
              servicePort: 8080
            path: /webhook/github
  tls:
    - hosts:
        - tekton.{{ .Values.global.appsDomainName }}
      secretName: {{ .Values.global.tlsCertIssuer }}
