apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: node-main-pipeline-trigger-template
spec:
  params:
    - name: project-name
      description: The repo name in GitHub, also used as the name for the Kaniko image
    - name: git-revision
      description: The revision to clone and build
    - name: git-branch
      description: the branch being built, either main|master or a feature branch (e.g. feature/5)
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: $(tt.params.project-name)-node-main-pipeline-run-
        namespace: greenlight-pipelines
      spec:
        pipelineRef:
          name: node-main-pipeline
        serviceAccountName: pipeline-sa
        params:
          - name: project-name
            value: $(tt.params.project-name)
          - name: git-revision
            value: $(tt.params.git-revision)  
          - name: git-branch
            value: $(tt.params.git-branch)  
        workspaces:
          - name: git-source
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
          - name: status-workspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Ki
          - name: greenlight-projects
            configMap:
              name: greenlight-projects
          - name: kubeconfig-dir
            emptyDir: {}
          - name: manifest-dir
            emptyDir: {}