apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: push-trigger-binding
  namespace: greenlight-pipelines
spec:
  params:
    - name: project-name
      value: $(body.repository.name)
    - name: git-revision
      value: $(body.after)
    - name: build-type
      value: $(extensions.build_type)

