apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: greenlight-verdaccio
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: greenlight-pipelines
    server: https://kubernetes.default.svc
  project: {{ .Values.spec.project }}
  source:
    repoURL: https://charts.verdaccio.org
    chart: verdaccio
    targetRevision: 4.6.2
    helm:
      releaseName: verdaccio
      values: |
        service:
          name: verdaccio
          port: 4873
        extraEnvVars:
        - name: GITHUBTOKEN
          valueFrom:
            secretKeyRef:
              name: bot-github-token
              key: botGithubTokenValue
        configMap: |
          listen: 0.0.0.0:4873
          storage: /verdaccio/storage/data
          web:
            enable: false
          uplinks:
            npmjs:
              url: https://registry.npmjs.org/
              agent_options:
                keepAlive: true
                maxSockets: 40
                maxFreeSockets: 10
            github:
              url: https://npm.pkg.github.com/
              auth:
                type: bearer
                token_env: GITHUBTOKEN
              agent_options:
                keepAlive: true
                maxSockets: 40
                maxFreeSockets: 10
          packages:
            '@greenlight-coop/*':
              access: $all
              publish: $all
              proxy: github
            '**':
              access: $all
              publish: $authenticated
              proxy: npmjs
        persistence:
          enabled: true
{{- if .Values.rook.enabled }}
          storageClass: rook-ceph-block
{{- end }}
          accessMode: ReadWriteOnce
          size: 8Gi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m