kind: Deployment
metadata:
  name: external-dns
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
        - name: external-dns
          image: registry.opensource.zalan.do/teapot/external-dns:latest
          args:
            - --source=service
            - --domain-filter=apps-feature-60.greenlightcoop.dev
            - --provider=google
            - --policy=sync
            - --registry=txt
            - --txt-owner-id=greenlight-coop-cluster