{{- if eq .Values.provider "linode" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.baseName }}-cert-manager-webhook-linode
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    path: base/cert-manager/cert-manager-webhook-linode
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }} 
    helm:
      releaseName: cert-manager-webhook-linode
      values: |
        api:
          groupName: greenlightcoop.dev
        deployment:
          secretName: linode-token
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
{{- end }}