---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-triggers-admin
  namespace: greenlight-pipelines
rules:
  # Permissions for every EventListener deployment to function
  - apiGroups:
      - triggers.tekton.dev
    resources:
      - eventlisteners
      - triggerbindings
      - triggertemplates
      - triggers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    # secrets are only needed for GitHub/GitLab interceptors
    resources:
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-pipelineruns-admin
  namespace: greenlight-pipeline-runs
rules:
  # Permissions to create resources in associated TriggerTemplates
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
      - pipelineresources
      - taskruns
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - impersonate
  - apiGroups:
      - ""
    # secrets are only needed for GitHub/GitLab interceptors
    resources:
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-triggers-admin
  namespace: greenlight-pipeline-runs

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-triggers-admin-binding
  namespace: greenlight-pipelines
subjects:
  - kind: ServiceAccount
    name: tekton-triggers-admin
    namespace: greenlight-pipeline-runs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-triggers-admin

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-pipelineruns-admin-binding
  namespace: greenlight-pipeline-runs
subjects:
  - kind: ServiceAccount
    name: tekton-triggers-admin
    namespace: greenlight-pipeline-runs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-pipelineruns-admin
