apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: openam-virtualservice
spec:
  gateways:
  - istio-system/istio-gateway
  hosts:
  - keycloak.{{ .Values.domainName }}
  http:
  - route:
    - destination:
        host: keycloak
        port:
          number: 8080
