apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: argo-cd-argocd-server
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-{{ .Values.useStagingCertificates | ternary "staging" "production" }}
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
spec:
  rules:
  - host: argocd.{{ .Values.appsDomainName }}
    http:
      paths:
      - backend:
          serviceName: argo-cd-argocd-server
          servicePort: 443
        path: /
  tls:
  - hosts:
    - argocd.{{ .Values.appsDomainName }}
    secretName: letsencrypt-{{ .Values.useStagingCertificates | ternary "staging" "production" }}