apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: argo-cd-argocd-server
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
spec:
  rules:
  - host: argocd-ingress.{{ .Values.appsDomainName }}
    http:
      paths:
      - backend:
          serviceName: argo-cd-argocd-server
          servicePort: 80
        path: /
  tls:
  - hosts:
    - argocd-ingress.{{ .Values.appsDomainName }}
    secretName: letsencrypt-{{ .Values.useStagingCertificates | ternary "staging" "production" }}