apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: argo-cd-argocd-server
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
spec:
  gateways:
  - argo-cd-argocd-server
  hosts:
  - grafana.{{ .Values.knativeDomainName }}
  tls:
  - match:
    - port: 443
      sniHosts:
      - grafana.{{ .Values.knativeDomainName }}
    route:
    - destination:
        host: argo-cd-argocd-server
        port:
          number: 443