apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: create-webhook-run
  namespace: getting-started
spec:
  taskRef:
    name: create-webhook
  params:
  - name: GitHubOrg
    value: "greenlight-coop"
  - name: GitHubUser
    value: "greenlight-coop-bot"
  - name: GitHubRepo
    value: "helloworld"
  - name: GitHubSecretName
    value: webhook-secret
  - name: GitHubAccessTokenKey
    value: token
  - name: GitHubSecretStringKey
    value: secret
  - name: ExternalDomain
    value: api-feature-10.greenlightcoop.dev
  timeout: 16m40s
  serviceAccountName: tekton-triggers-createwebhook
