apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-operator
spec:
  values:
    global:
      proxy:
        autoInject: enabled
      useMCP: false
      # The third-party-jwt is not enabled on all k8s.
      # See: https://istio.io/docs/ops/best-practices/security/#configure-third-party-service-account-tokens
      jwtPolicy: {{ .Values.jwtPolicy }}

  addonComponents:
    pilot:
      enabled: true
    prometheus:
      enabled: false

  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          serviceAnnotations:
            external-dns.alpha.kubernetes.io/hostname: '{{ .Values.domainName }},*.{{ .Values.domainName }}'
          {{- if .Values.httpNodePort }}
          service:
            type: NodePort
            ports:
            - port: 80
              name: http2
              targetPort: 8080
              nodePort: {{ .Values.httpNodePort }}
            - port: 443
              name: https
              targetPort: 8443
              nodePort: {{ .Values.httpsNodePort }}
          {{- end }}

  meshConfig:
    accessLogFile: /dev/stdout
