{{- if .Values.certManager.generateCerts }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-istio-system-issuer
  namespace: istio-system
spec:
  acme:
    email: {{ .Values.adminEmail }}
    server: {{ .Values.useStagingCertificates | ternary "https://acme-staging-v02.api.letsencrypt.org/directory" "https://acme-v02.api.letsencrypt.org/directory" }}
    privateKeySecretRef:
      name: letsencrypt-issuer-tls-key
    solvers:
    - dns01:
  {{- if eq .Values.provider "google" }}
        cloudDNS:
          project: {{ .Values.googleProjectId }}
  {{- else if eq .Values.provider "linode" }}
        webhook:
          solverName: linode
          groupName: greenlightcoop.dev
          config:
            apiKeySecretRef:
              name: linode-token
              key: token
  {{- else if eq .Values.provider "digitalocean" }}
        digitalocean:
          tokenSecretRef:
            name: digitalocean-token
            key: token
  {{- end }}
{{- end }}
