adminEmail: ""
baseName: ""
domainName: ""
googleProjectId: ""
provider: ""
spec:
  destination:
    server: ""
  project: ""
  source:
    repoURL: ""
    targetRevision: ""
useStagingCertificates: ""
