# apiVersion: serving.knative.dev/v1
# kind: Service
# metadata:
#   name: helloworld
#   namespace: staging
# spec:
#   template:
#     spec:
#       containers:
#       - image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld
  namespace: default
spec:
  template:
    metadata:
      annotations:
        # Target 10 in-flight-requests per pod.
        autoscaling.knative.dev/target: "10"
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
