dependencies:
- name: loki
  version: 2.0.0
  repository: https://grafana.github.io/loki/charts
- name: grafana
  version: 3.4.7
  repository: https://charts.bitnami.com/bitnami
- name: prometheus
  version: 2.2.2
  repository: https://charts.bitnami.com/bitnami
