grafana:
  admin:
    existingSecret: admin-password-secret
    existingSecretPasswordKey: password
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx 
      cert-manager.io/cluster-issuer: letsencrypt-production
    hosts:
    - name: grafana.apps.greenlightcoop.dev
      tls: true
      tlsSecret: letsencrypt-production
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://monitoring-loki:3100
        isDefault: true
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://monitoring-prometheus-server
