grafana:
  ingress:
    enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx 
    cert-manager.io/cluster-issuer: letsencrypt-production
  hosts:
    - host: grafana-temp3.dev.greenlight.coop
  tls:
  - secretName: letsencrypt-production
    hosts:
      - grafana-temp3.dev.greenlight.coop  
  service:
    type: LoadBalancer
  datasources:
    datasources.yaml:
      apiVersion: v2
      datasources:
      - name: Loki
        type: loki
        url: http://loki:3100
        access: proxy
        isDefault: true
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server
        access: proxy
