grafana:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx 
      cert-manager.io/cluster-issuer: letsencrypt-production
    hosts:
      - name: grafana.dev.greenlight.coop
        tls: true
        tlsSecret: letsencrypt-production
  datasources:
    datasources.yaml:
      apiVersion: v2
      datasources:
      - name: Loki
        type: loki
        url: http://loki:3100
        access: proxy
        isDefault: true
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server
        access: proxy
