loki-stack:
  fluent-bit:
    enabled: true
  grafana:
    enabled: true
  prometheus:
    enabled: true
    alertmanager:
      persistentVolume:
        enabled=false
    server:
      persistentVolume:
        enabled=false