knativeDomainName: ""
useStagingCertificates: ""
googleProjectId: ""
grafana:
  admin:
    existingSecret: grafana-admin-password-secret
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://monitoring-loki:3100
        isDefault: true
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://monitoring-prometheus-server