grafana:
  admin:
    existingSecret: grafana-admin-password-secret
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: kong 
      cert-manager.io/cluster-issuer: letsencrypt-production
    hosts:
    - grafana.kong.greenlightcoop.dev
    tls:
    - secretName: letsencrypt-production
      hosts:
      - grafana.kong.greenlightcoop.dev
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://monitoring-loki:3100
        isDefault: true
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://monitoring-prometheus-server
