apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helloworld
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: staging
    server: {{ .Values.spec.destination.server }}
  project: greenlight-project
  source:
    path: helloworld
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    # helm:
    #   parameters:
    #   - name: "global.workspaceSuffix"
    #     value: {{ .Values.spec.source.helm.global.workspaceSuffix }}
    #   - name: "ingress.tls[0].secretName"
    #     value: ${tls_secret_name}