apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helloworld
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: staging
    server: {{ .Values.spec.destination.server }}
  project: greenlight-project
  source:
    path: helloworld
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      parameters:
      - name: "global.ingress.hosts[0].host"
        value: api{{ .Values.spec.source.helm.global.workspaceSuffix }}.dev.greenlight.coop
      - name: "global.ingress.tls[0].hosts[0]"
        value: {{ .Values.spec.source.helm.global.tlsSecretName }}
