apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8ssandra-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: k8ssandra-dev
    server: {{ .Values.spec.destination.server }}
  project: greenlight-project
  source:
    repoURL: https://helm.k8ssandra.io/
    chart: k8ssandra
    targetRevision: 0.38.0
  syncPolicy:
    syncOptions:
      - CreateNamespace=true 
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
