apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: {{ .Values.spec.destination.server }}
  project: greenlight-project
  source:
    path: monitoring
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.global.targetRevision }}
    helm:
      values: |
        appsDomainName: {{ .Values.global.appsDomainName }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m