apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: {{ .Values.spec.destination.server }}
  project: greenlight-project
  source:
    path: monitoring
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.global.targetRevision }}
    helm:
      parameters:
        - name: "grafana.ingress.annotations.cert-manager\\.io/cluster-issuer"
          value: {{ .Values.global.tlsCertIssuer }}
        - name: "grafana.ingress.hosts[0].name"
          value: grafana{{ .Values.global.workspaceSuffix }}.dev.greenlight.coop,grafana.ingress.hosts[0].tls=true,grafana.ingress.hosts[0].tlsSecret={{ .Values.global.tlsSecretName }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
