apiVersion: v1
kind: Namespace
metadata:
  name: staging
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: test
  annotations:
    argocd.argoproj.io/sync-wave: "-1"