apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: argocd-server
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
spec:
  gateways:
  - istio-system/istio-gateway
  hosts:
  - argocd.{{ .Values.domainName }}
  http:
  - route:
    - destination:
        host: argocd-server
        port:
          number: 80
