apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.baseName }}-monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    path: base/monitoring/apps
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      releaseName: monitoring
      values: |
        baseName: {{ .Values.baseName }}
        domainName: {{ .Values.domainName }}
        kubePrometheusStack:
          enabled: {{ .Values.kubePrometheusStack.enabled }}
        nodeLogging:
{{- if eq .Values.provider "kind" }}
          enabled: false
{{- else }}
          enabled: true
{{- end }}
        spec:
          destination:
            server: {{ .Values.spec.destination.server }}
          project: {{ .Values.spec.project }}
          source:
            repoURL: {{ .Values.spec.source.repoURL }}
            targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m