{{- if .Values.cassandra.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.baseName }}-k8ssandra
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "9"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: k8ssandra-operator
    server: https://kubernetes.default.svc
  project: {{ .Values.spec.project }}
  source:
    path: base/k8ssandra/apps
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      releaseName: k8ssandra
      values: |
        baseName: {{ .Values.baseName }}
        rook:
          enabled: {{ .Values.rook.enabled }}
        spec:
          destination:
            server: {{ .Values.spec.destination.server }}
          project: {{ .Values.spec.project }}
          source:
            repoURL: {{ .Values.spec.source.repoURL }}
            targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
{{- end }}