{{- if .Values.cassandra.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.baseName }}-k8ssandra
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "9"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    path: base/k8ssandra/charts/k8ssandra
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      releaseName: k8ssandra
      values: |
        cassandra:
          version: "4.0.1"
          allowMultipleNodesPerWorker: true
  {{- if .Values.rook.enabled }}
          cassandraLibDirVolume:
            storageClass: rook-ceph-block-waitforfirstconsumer
  {{- end }}
          heap:
            size: 1G
            newGenSize: 1G
          resources:
            requests:
              cpu: 1000m
              memory: 2Gi
            limits:
              cpu: 1000m
              memory: 2Gi
          datacenters:
          - name: dc1
            size: 1
            racks:
            - name: default
        kube-prometheus-stack:
          grafana:
            datasources:
              datasources.yaml:
                apiVersion: 1
                datasources:
                - name: Loki
                  type: loki
                  access: proxy
                  url: http://loki:3100
        stargate:
          enabled: false
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
{{- end }}