apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: openam-virtualservice
spec:
  gateways:
  - istio-system/istio-gateway
  hosts:
  - openam.{{ .Values.domainName }}
  http:
  - match:
    - uri:
        prefix: /
    rewrite:
      uri: /openam
    route:
    - destination:
        host: openam
        port:
          number: 8080
