apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 2048-game-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: game-2048
    server: {{ .Values.spec.destination.server }}
  project: greenlight-project
  source:
    path: kustomize
    repoURL: https://github.com/greenlight-coop/tekton-pipeline-example-app.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
