apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-argocd-example-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: tekton-argocd-example
    server: {{ .Values.spec.destination.server }}
  project: greenlight-project
  source:
    path: tekton-example/tekton-pipeline-example-pipeline/resources
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.global.targetRevision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
