kube-prometheus-stack:
  grafana:
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          url: http://loki:3100
    plugins:
    - grafana-polystat-panel