apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-minimal-operator
spec:
  values:
    global:
      proxy:
        autoInject: disabled
      useMCP: false
      # The third-party-jwt is not enabled on all k8s.
      # See: https://istio.io/docs/ops/best-practices/security/#configure-third-party-service-account-tokens
      {{ if .Values.kind }}
      jwtPolicy: first-party-jwt
      {{ else }}
      jwtPolicy: third-party-jwt
      {{ end }}

  addonComponents:
    pilot:
      enabled: true
    prometheus:
      enabled: false

  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        {{ if .Values.kind }}
        k8s:
          service:
            type: NodePort
            ports:
            - port: 30080
              name: http2
              targetPort: 8080
              nodePort: 30080
            - port: 30443
              name: https
              targetPort: 8443      
              nodePort: 30443
        {{ end }}
      - name: cluster-local-gateway
        enabled: true
        label:
          istio: cluster-local-gateway
          app: cluster-local-gateway
        k8s:
          service:
            type: ClusterIP
            ports:
            - port: 15020
              name: status-port
            - port: 80
              name: http2
              targetPort: 8080
            - port: 443
              name: https
              targetPort: 8443