apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-discovery
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: istio-system
    server: {{ .Values.spec.destination.server }}
  project: greenlight-project
  source:
    path: istio/istio-1.8.0/manifests/charts/istio-control/istio-discovery
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.global.targetRevision }}
    helm:
      values: |
        global:
          hub: docker.io/istio
          tag: docker.io/1.8.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m