apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    # cert-manager.io/cluster-issuer: letsencrypt-{{ .Values.useStagingCertificates | ternary "staging" "production" }}
    kubernetes.io/ingress.class: istio
  labels:
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 7.3.5
    argocd.argoproj.io/instance: monitoring
    helm.sh/chart: grafana-6.1.16
  name: monitoring-grafana
  namespace: default
spec:
  rules:
  - host: grafana.{{ .Values.knativeDomainName }}
    http:
      paths:
      - backend:
          serviceName: monitoring-grafana
          servicePort: 80
        path: /*
  # tls:
  # - hosts:
  #   - grafana.{{ .Values.knativeDomainName }}
  #   secretName: letsencrypt-{{ .Values.useStagingCertificates | ternary "staging" "production" }}-grafana
