apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: monitoring-grafana
  namespace: default
  labels:
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 7.3.5
    argocd.argoproj.io/instance: monitoring
spec:
  gateways:
  - monitoring-grafana
  hosts:
  - grafana.{{ .Values.knativeDomainName }}
  http:
  - match:
    - uri:
        prefix: /