apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  labels:
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 7.3.5
    argocd.argoproj.io/instance: monitoring
  name: monitoring-grafana
  namespace: default
spec:
  rules:
  - host: grafana.{{ .Values.knativeDomainName }}
    http:
      paths:
      - backend:
          serviceName: monitoring-grafana
          servicePort: 80
        path: /*
  # tls:
  # - hosts:
  #   - grafana.{{ .Values.knativeDomainName }}
  #   secretName: letsencrypt-{{ .Values.useStagingCertificates | ternary "staging" "production" }}-grafana
