apiVersion: v1
kind: ConfigMap
metadata:
  name: config-network
  namespace: knative-serving
  labels:
    serving.knative.dev/release: "v0.19.0"
  annotations:
    knative.dev/example-checksum: "5e3df87d"
data:
  autoTLS: Enabled
  httpProtocol: Enabled
  