apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.baseName }}-istio-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: istio-system
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    path: base/istio/istio-config
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      releaseName: istio-config
      values: |
        adminEmail: {{ .Values.adminEmail }}
        certManager:
          enabled: {{ .Values.certManager.enabled }}
        domainName: {{ .Values.domainName }}
        googleProjectId: {{ .Values.googleProjectId }}
        httpNodePort: {{ .Values.httpNodePort }}
        httpsNodePort: {{ .Values.httpsNodePort }}
        jwtPolicy: {{ .Values.jwtPolicy }}
        provider: {{ .Values.provider }}
        useStagingCertificates: {{ .Values.useStagingCertificates }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m