apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-kiali-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kiali-operator
    server: {{ .Values.spec.destination.server }}
  project: greenlight-project
  source:
    repoURL: https://kiali.org/helm-charts
    chart: kiali-operator
    targetRevision: 1.28.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m 