apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: monitoring-grafana
  namespace: default
  labels:
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 7.3.5
    argocd.argoproj.io/instance: monitoring
spec:
  gateways:
  - istio-system/istio-gateway
  hosts:
  - grafana.{{ .Values.domainName }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        {{- if .Values.kubePrometheusStack.enabled }}
        host: prometheus-grafana
        {{- else }}
        host: k8ssandra-grafana
        {{- end }}
