apiVersion: v1
kind: Secret
metadata:
  name: basic-docker-user-pass
  annotations:
    # Replace <docker_registry_url> with your docker registry URL (e.g. https://my-acr.azurecr.io)
    tekton.dev/docker-0: https://docker.io
type: kubernetes.io/basic-auth
stringData:
  username: greenlightcoopbot
  password: 167hHKFyf2%*