apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: close-pr-pipeline-service
  namespace: greenlight-pipelines
spec:
  params:
    - name: project-name
      type: string
    - name: repository-full-name
      type: string
    - name: hub-organization
      type: string
    - name: git-revision
      type: string
    - name: git-branch
      type: string
    - name: git-pr-number
      type: string
    - name: git-pr-commit-number
      type: string
    - name: preview-namespace
      type: string
  workspaces:
    - name: status-workspace
    - name: kubeconfig-dir
    - name: manifest-dir
    - name: node-modules
  tasks:
    - name: set-default-outcome
      taskRef:
        name: set-outcome-status
      params:
        - name: status
          value: failure
      workspaces:
        - name: status-workspace
          workspace: status-workspace
    - name: publish-pending-status-to-github
      taskRef:
        name: github-set-status
      params:
        - name: REPO_FULL_NAME
          value: $(params.repository-full-name)
        - name: SHA
          value: $(params.git-revision)
        - name: GITHUB_TOKEN_SECRET_NAME
          value: bot-github-token
        - name: GITHUB_TOKEN_SECRET_KEY
          value: botGithubTokenValue
        - name: STATE
          value: pending
        - name: DESCRIPTION
          value: Build started
        - name: TARGET_URL
          value: https://dashboard.{{ .Values.domainName }}/#/namespaces/greenlight-pipelines/pipelineruns/$(context.pipelineRun.name)
    - name: uninstall-preview-chart
      taskRef:
        name: uninstall-helm-chart
      params:
        - name: namespace
          value: $(params.preview-namespace)
        - name: release-name
          value: preview
    - name: delete-preview-resources
      taskRef:
        name: kubernetes-actions
      runAfter:
        - uninstall-preview-chart
      params:
        - name: script
          value: |
            kubectl delete --namespace argocd --ignore-not-found applications.argoproj.io $(params.preview-namespace)
    - name: delete-pr-namespace
      taskRef:
        name: kubernetes-actions
      runAfter:
        - uninstall-preview-chart
      params:
        - name: script
          value: |
            kubectl delete --ignore-not-found namespace $(params.preview-namespace)
      workspaces:
        - name: kubeconfig-dir
          workspace: kubeconfig-dir
        - name: manifest-dir
          workspace: manifest-dir
    - name: delete-pull-request-images
      taskRef:
        name: delete-pull-request-images
      params:
        - name: organization
          value: $(params.hub-organization)
        - name: repository
          value: $(params.project-name)
        - name: pull-request-number
          value: $(params.git-pr-number)
      workspaces:
        - name: node-modules
          workspace: node-modules
    - name: set-success-outcome
      taskRef:
        name: set-outcome-status
      runAfter:
        - set-default-outcome
        - uninstall-preview-chart
        - delete-preview-resources
        - delete-pr-namespace
        - delete-pull-request-images
      params:
        - name: status
          value: success
      workspaces:
        - name: status-workspace
          workspace: status-workspace
  finally:
    - name: publish-outcome-status-to-github
      taskRef:
        name: github-set-status-from-outcome
      workspaces:
        - name: status-workspace
          workspace: status-workspace
      params:
        - name: REPO_FULL_NAME
          value: $(params.repository-full-name)
        - name: SHA
          value: $(params.git-revision)
        - name: GITHUB_TOKEN_SECRET_NAME
          value: bot-github-token
        - name: GITHUB_TOKEN_SECRET_KEY
          value: botGithubTokenValue
        - name: DESCRIPTION
          value: Build complete
        - name: TARGET_URL
          value: https://dashboard.{{ .Values.domainName }}/#/namespaces/greenlight-pipelines/pipelineruns/$(context.pipelineRun.name)
