apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pr-pipeline-service
  namespace: greenlight-pipelines
spec:
  params:
    - name: project-name
      type: string
    - name: repository-full-name
      type: string
    - name: hub-organization
      type: string
    - name: git-revision
      type: string
    - name: git-branch
      type: string
    - name: git-pr-number
      type: string
    - name: git-pr-commit-number
      type: string
    - name: preview-namespace
      type: string
  workspaces:
    - name: git-source
    - name: status-workspace
    - name: node-modules
    - name: kubeconfig-dir
    - name: manifest-dir
  tasks:
    - name: set-default-outcome
      taskRef:
        name: set-outcome-status
      params:
        - name: status
          value: failure
      workspaces:
        - name: status-workspace
          workspace: status-workspace
    - name: publish-pending-status-to-github
      taskRef:
        name: github-set-status
      params:
        - name: REPO_FULL_NAME
          value: $(params.repository-full-name)
        - name: SHA
          value: $(params.git-revision)
        - name: GITHUB_TOKEN_SECRET_NAME
          value: bot-github-token
        - name: GITHUB_TOKEN_SECRET_KEY
          value: botGithubTokenValue
        - name: STATE
          value: pending
        - name: DESCRIPTION
          value: Build started
        - name: TARGET_URL
          value: https://dashboard.{{ .Values.domainName }}/#/namespaces/greenlight-pipelines/pipelineruns/$(context.pipelineRun.name)
    - name: has-preview
      taskRef:
        name: has-preview
      runAfter:
        - clone-git-repo
      workspaces:
        - name: source
          workspace: git-source
    - name: ensure-preview-namespace-exists
      taskRef:
        name: kubernetes-actions
      when:
        - input: "$(tasks.has-preview.results.value)"
          operator: in
          values: ["true"]
      params:
        - name: script
          value: |
            cat <<EOF | kubectl apply -f -
            apiVersion: v1
            kind: Namespace
            metadata:
              name: $(params.preview-namespace)
              labels:
                istio-injection: enabled
            EOF
      workspaces:
        - name: kubeconfig-dir
          workspace: kubeconfig-dir
        - name: manifest-dir
          workspace: manifest-dir    
    - name: clone-git-repo
      taskRef:
        name: git-clone
      params:
        - name: url
          value: git@github.com:$(params.repository-full-name).git
        - name: revision
          value: $(params.git-revision)
      workspaces:
        - name: output
          workspace: git-source
    - name: generate-npmrc
      taskRef:
        name: generate-npmrc
      runAfter:
        - clone-git-repo
      params:
        - name: githubTokenSecretName
          value: bot-github-token
        - name: githubTokenSecretKey
          value: botGithubTokenValue
      workspaces:
        - name: source
          workspace: git-source
    - name: snyk-test
      taskRef:
        name: snyk-test
      runAfter:
        - clone-git-repo
        - generate-npmrc
      workspaces:
        - name: source
          workspace: git-source
    - name: version-node-package
      taskRef:
        name: version-node-package
      runAfter:
        - clone-git-repo
        - generate-npmrc
      params:
        - name: push-git
          value: "false"
        - name: branch-name
          value: $(params.git-branch)
        - name: pull-request-number
          value: $(params.git-pr-number)
        - name: pull-request-commit-number
          value: $(params.git-pr-commit-number)
      workspaces:
        - name: source
          workspace: git-source
    - name: build-and-push-image
      taskRef:
        name: buildkit
      runAfter:
        - snyk-test
        - generate-npmrc
      params:
        - name: IMAGE
          value: $(params.hub-organization)/$(params.project-name):$(tasks.version-node-package.results.node-version)
        - name: BUILDKIT_CLIENT_IMAGE
          value: moby/buildkit:v0.10.1@sha256:bd37f0b5567084cd6f4b1c73b7fed9e12258441d064cc2add29a7dd32243ff86
      workspaces:
        - name: source
          workspace: git-source
    - name: snyk-container-test
      taskRef:
        name: snyk-container-test
      runAfter:
        - build-and-push-image
      params:
        - name: image
          value: $(params.hub-organization)/$(params.project-name):$(tasks.version-node-package.results.node-version)
      workspaces:
        - name: source
          workspace: git-source
    - name: helm-lint
      taskRef:
        name: helm-lint
      runAfter:
        - clone-git-repo
      workspaces:
        - name: source
          workspace: git-source
    - name: deploy-preview-chart
      taskRef:
        name: deploy-preview-chart
      when:
        - input: "$(tasks.has-preview.results.value)"
          operator: in
          values: ["true"]
      runAfter:
        - helm-lint
        - snyk-test
        - snyk-container-test
        - ensure-preview-namespace-exists
      params:
        - name: project-name
          value: $(params.project-name)
        - name: namespace
          value: $(params.preview-namespace)
      workspaces:
        - name: source
          workspace: git-source
    - name: run-integration-tests
      taskRef:
        name: run-serenity-tests
      when:
        - input: "$(tasks.has-preview.results.value)"
          operator: in
          values: ["true"]
      runAfter:
        - deploy-preview-chart
      params:
        - name: base-url
          value: http://preview-$(params.project-name).$(params.preview-namespace).svc.cluster.local
        - name: results-identifier
          value: $(params.preview-namespace)
      workspaces:
        - name: source
          workspace: git-source
    - name: set-success-outcome
      taskRef:
        name: set-outcome-status
      runAfter:
        - set-default-outcome
        - helm-lint
        - run-integration-tests
        - snyk-test
        - snyk-container-test
      params:
        - name: status
          value: success
      workspaces:
        - name: status-workspace
          workspace: status-workspace
  finally:
    - name: publish-outcome-status-to-github
      taskRef:
        name: github-set-status-from-outcome
      workspaces:
        - name: status-workspace
          workspace: status-workspace
      params:
        - name: REPO_FULL_NAME
          value: $(params.repository-full-name)
        - name: SHA
          value: $(params.git-revision)
        - name: GITHUB_TOKEN_SECRET_NAME
          value: bot-github-token
        - name: GITHUB_TOKEN_SECRET_KEY
          value: botGithubTokenValue
        - name: DESCRIPTION
          value: Build complete
        - name: TARGET_URL
          value: https://dashboard.{{ .Values.domainName }}/#/namespaces/greenlight-pipelines/pipelineruns/$(context.pipelineRun.name)
