apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pr-pipeline-helm
  namespace: greenlight-pipelines
spec:
  params:
    - name: project-name
      type: string
    - name: repository-full-name
      type: string
    - name: hub-organization
      type: string
    - name: git-revision
      type: string
    - name: git-branch
      type: string
    - name: git-pr-number
      type: string
    - name: git-pr-commit-number
      type: string
  workspaces:
    - name: git-source
    - name: helm-git-source
    - name: status-workspace
    - name: node-modules
    - name: kubeconfig-dir
    - name: manifest-dir
  tasks:
    - name: set-default-outcome
      taskRef:
        name: set-outcome-status
      params:
        - name: status
          value: failure
      workspaces:
        - name: status-workspace
          workspace: status-workspace
    - name: publish-pending-status-to-github
      taskRef:
        name: github-set-status
      params:
        - name: REPO_FULL_NAME
          value: $(params.repository-full-name)
        - name: SHA
          value: $(params.git-revision)
        - name: GITHUB_TOKEN_SECRET_NAME
          value: bot-github-token
        - name: GITHUB_TOKEN_SECRET_KEY
          value: botGithubTokenValue
        - name: STATE
          value: pending
        - name: DESCRIPTION
          value: Build started
        - name: TARGET_URL
          value: https://dashboard.{{ .Values.domainName }}/#/namespaces/greenlight-pipelines/pipelineruns/$(context.pipelineRun.name)
    - name: clone-git-repo
      taskRef:
        name: git-clone
      params:
        - name: url
          value: git@github.com:$(params.repository-full-name).git
        - name: revision
          value: $(params.git-revision)
      workspaces:
        - name: output
          workspace: git-source
    - name: clone-helm-git-repo
      taskRef:
        name: git-clone
      params:
        - name: url
          value: git@github.com:greenlight-coop/greenlight-helm-charts.git
        - name: revision
          value: HEAD
      workspaces:
        - name: output
          workspace: helm-git-source
    - name: generate-npmrc
      taskRef:
        name: generate-npmrc
      runAfter:
        - clone-git-repo
      params:
        - name: githubTokenSecretName
          value: bot-github-token
        - name: githubTokenSecretKey
          value: botGithubTokenValue
      workspaces:
        - name: source
          workspace: git-source
    - name: version-node-package
      taskRef:
        name: version-node-package
      runAfter:
        - clone-git-repo
        - generate-npmrc
      params:
        - name: push-git
          value: "false"
        - name: branch-name
          value: $(params.git-branch)
        - name: pull-request-number
          value: $(params.git-pr-number)
        - name: pull-request-commit-number
          value: $(params.git-pr-commit-number)
      workspaces:
        - name: source
          workspace: git-source
    - name: helm-package
      taskRef:
        name: helm-package
      runAfter:
        - version-node-package
        - clone-helm-git-repo
      params:
        - name: push-git
          value: "false"
        - name: version
          value: $(tasks.version-node-package.results.node-version)
      workspaces:
        - name: source
          workspace: git-source
        - name: helm
          workspace: helm-git-source
    - name: set-success-outcome
      taskRef:
        name: set-outcome-status
      runAfter:
        - set-default-outcome
        - helm-package
      params:
        - name: status
          value: success
      workspaces:
        - name: status-workspace
          workspace: status-workspace
  finally:
    - name: publish-outcome-status-to-github
      taskRef:
        name: github-set-status-from-outcome
      workspaces:
        - name: status-workspace
          workspace: status-workspace
      params:
        - name: REPO_FULL_NAME
          value: $(params.repository-full-name)
        - name: SHA
          value: $(params.git-revision)
        - name: GITHUB_TOKEN_SECRET_NAME
          value: bot-github-token
        - name: GITHUB_TOKEN_SECRET_KEY
          value: botGithubTokenValue
        - name: DESCRIPTION
          value: Build complete
        - name: TARGET_URL
          value: https://dashboard.{{ .Values.domainName }}/#/namespaces/greenlight-pipelines/pipelineruns/$(context.pipelineRun.name)
