apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test-stage-close-pr-pipeline
  namespace: greenlight-pipelines
spec:
  params:
    - name: project-name
      type: string
    - name: repository-full-name
      type: string
    - name: git-revision
      type: string
    - name: git-pr-number
      type: string
  workspaces:
    - name: git-source
    - name: status-workspace
    - name: kubeconfig-dir
    - name: manifest-dir
  tasks:
    - name: set-default-outcome
      taskRef:
        name: set-outcome-status
      params:
        - name: status
          value: failure
      workspaces:
        - name: status-workspace
          workspace: status-workspace
    - name: publish-pending-status-to-github
      taskRef:
        name: github-set-status
      params:
        - name: REPO_FULL_NAME
          value: $(params.repository-full-name)
        - name: SHA
          value: $(params.git-revision)
        - name: GITHUB_TOKEN_SECRET_NAME
          value: bot-github-token
        - name: GITHUB_TOKEN_SECRET_KEY
          value: botGithubTokenValue
        - name: STATE
          value: pending
        - name: DESCRIPTION
          value: Build started
        - name: TARGET_URL
          value: https://dashboard.{{ .Values.domainName }}/#/namespaces/greenlight-pipelines/pipelineruns/$(context.pipelineRun.name)
    - name: delete-test-stage-resources
      taskRef:
        name: kubernetes-actions
      params:
        - name: script
          value: |
            set -ex            
            kubectl delete --ignore-not-found --namespace argocd applications.argoproj.io api-$(params.project-name)-pr-$(params.git-pr-number)
            kubectl delete --ignore-not-found --namespace argocd applications.argoproj.io ui-$(params.project-name)-pr-$(params.git-pr-number)
            kubectl delete --ignore-not-found --namespace argocd applications.argoproj.io $(params.project-name)-pr-$(params.git-pr-number)-deployment
      workspaces:
        - name: kubeconfig-dir
          workspace: kubeconfig-dir
        - name: manifest-dir
          workspace: manifest-dir
    - name: uninstall-application-chart
      taskRef:
        name: uninstall-helm-chart
      params:
        - name: namespace
          value: $(params.project-name)-pr-$(params.git-pr-number)
        - name: release-name
          value: $(params.project-name)-pr-$(params.git-pr-number)
    - name: delete-test-stage-namespace
      taskRef:
        name: kubernetes-actions
      runAfter:
        - delete-test-stage-resources
        - uninstall-application-chart
      params:
        - name: script
          value: |
            kubectl delete --ignore-not-found namespace $(params.project-name)-pr-$(params.git-pr-number)
      workspaces:
        - name: kubeconfig-dir
          workspace: kubeconfig-dir
        - name: manifest-dir
          workspace: manifest-dir
      workspaces:
        - name: kubeconfig-dir
          workspace: kubeconfig-dir
        - name: manifest-dir
          workspace: manifest-dir
    - name: set-success-outcome
      taskRef:
        name: set-outcome-status
      runAfter:
        - delete-test-stage-resources
        - delete-test-stage-namespace
      params:
        - name: status
          value: success
      workspaces:
        - name: status-workspace
          workspace: status-workspace
  finally:
    - name: publish-outcome-status-to-github
      taskRef:
        name: github-set-status-from-outcome
      workspaces:
        - name: status-workspace
          workspace: status-workspace
      params:
        - name: REPO_FULL_NAME
          value: $(params.repository-full-name)
        - name: SHA
          value: $(params.git-revision)
        - name: GITHUB_TOKEN_SECRET_NAME
          value: bot-github-token
        - name: GITHUB_TOKEN_SECRET_KEY
          value: botGithubTokenValue
        - name: DESCRIPTION
          value: Build complete
        - name: TARGET_URL
          value: https://dashboard.{{ .Values.domainName }}/#/namespaces/greenlight-pipelines/pipelineruns/$(context.pipelineRun.name)
