apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: sso
spec:
  hosts:
  - keycloak.{{ .Values.domainName }}
  gateways:
  - keycloak-gateway
  tls:
  - match:
    - port: 443
      sniHosts:
      - keycloak.{{ .Values.domainName }}
    route:
    - destination:
        port:
          number: 8443
        host: keycloak