apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: sso
spec:
  gateways:
  - istio-system/istio-gateway
  hosts:
  - keycloak.{{ .Values.domainName }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 8443
        host: keycloak