apiVersion: v1
kind: Service
metadata:
  labels:
    app: keycloak
  name: keycloak-http
  namespace: keycloak
spec:
  type: ClusterIP
  selector:
    app: keycloak
    component: keycloak
  ports:
    - name: keycloak-http
      port: 8080
      protocol: TCP
      targetPort: 8080
