apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  instances: {{ .Values.keycloak.instances }} 
  extensions:
    - https://github.com/aerogear/keycloak-metrics-spi/releases/download/2.5.3/keycloak-metrics-spi-2.5.3.jar
  externalAccess:
    enabled: false
    host: keycloak.{{ .Values.domainName }}
  podDisruptionBudget:
    enabled: true
{{- if .Values.rook.enabled }}
  storageClassName: rook-ceph-block
{{- end }}