apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: getting-started
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: getting-started
    server: {{ .Values.spec.destination.server }}
  project: greenlight-project
  source:
    path: continuous-integration/getting-started
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.global.targetRevision }}
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
