apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test-stage-pr-pipeline
  namespace: greenlight-pipelines
spec:
  params:
    - name: project-name
      type: string
    - name: git-revision
      type: string
    - name: git-pr-number
      type: string
  workspaces:
    - name: git-source
    - name: status-workspace
    - name: node-modules
    - name: kubeconfig-dir
    - name: manifest-dir
  tasks:
    - name: set-default-outcome
      taskRef:
        name: set-outcome-status
      params:
        - name: status
          value: failure
      workspaces:
        - name: status-workspace
          workspace: status-workspace
    - name: publish-pending-status-to-github
      taskRef:
        name: github-set-status
      params:
        - name: REPO_FULL_NAME
          value: greenlight-coop/$(params.project-name)
        - name: SHA
          value: $(params.git-revision)
        - name: GITHUB_TOKEN_SECRET_NAME
          value: bot-github-token
        - name: GITHUB_TOKEN_SECRET_KEY
          value: botGithubTokenValue
        - name: STATE
          value: pending
        - name: DESCRIPTION
          value: Build started
        - name: TARGET_URL
          value: https://dashboard.{{ .Values.appsDomainName }}/#/namespaces/greenlight-pipelines/pipelineruns/$(context.pipelineRun.name)
    - name: clone-git-repo
      taskRef:
        name: git-clone
      params:
        - name: url
          value: git@github.com:greenlight-coop/$(params.project-name).git
        - name: revision
          value: $(params.git-revision)
      workspaces:
        - name: output
          workspace: git-source  
    - name: parse-templates
      taskRef:
        name: parse-templates
      runAfter:
        - clone-git-repo
      params:
        - name: values
          value: |
            prNumber: $(params.git-pr-number)
            appsDomainName: {{ .Values.appsDomainName }}
            knativeDomainName: {{ .Values.knativeDomainName }}
            useStagingCertificates: {{ .Values.useStagingCertificates }}
      workspaces:
        - name: template-directory
          workspace: git-source
    - name: deploy-test-stage
      taskRef:
        name: apply-manifest
      runAfter:
        - parse-templates
      params:
        - name: manifest-path
          value: $(params.project-name).yaml
      workspaces:
        - name: source
          workspace: git-source
    - name: get-api-functional-test-image
      taskRef:
        name: get-command-output
      runAfter:
        - deploy-test-stage
      params:
        - name: command
          value: |
            kubectl get application -n argocd greenlight-stage-test-pr-$(params.git-pr-number) \
              -o jsonpath="{.metadata.annotations['greenlightcoop\.dev/test-image']}"
    - name: run-api-functional-tests
      taskRef:
        name: run-serenity-tests
      runAfter:
        - deploy-test-stage
      params:
        - name: test-image
          value: $(tasks.get-api-functional-test-image.results.output)
        - name: base-url
          value: https://helloworld.test-pr-$(params.git-pr-number).{{ .Values.knativeDomainName }}
        - name: results-identifier
          value: test-pr-$(params.git-pr-number)
      workspaces:
        - name: source
          workspace: git-source
    - name: set-success-outcome
      taskRef:
        name: set-outcome-status
      runAfter:
        - deploy-test-stage
        - run-api-functional-tests
      params:
        - name: status
          value: success
      workspaces:
        - name: status-workspace
          workspace: status-workspace
  finally:
    - name: publish-outcome-status-to-github
      taskRef:
        name: github-set-status-from-outcome
      workspaces:
        - name: status-workspace
          workspace: status-workspace
      params:
        - name: REPO_FULL_NAME
          value: greenlight-coop/$(params.project-name)
        - name: SHA
          value: $(params.git-revision)
        - name: GITHUB_TOKEN_SECRET_NAME
          value: bot-github-token
        - name: GITHUB_TOKEN_SECRET_KEY
          value: botGithubTokenValue
        - name: DESCRIPTION
          value: Build complete
        - name: TARGET_URL
          value: https://dashboard.{{ .Values.appsDomainName }}/#/namespaces/greenlight-pipelines/pipelineruns/$(context.pipelineRun.name)
