apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: k8ssandra
spec:
  cassandra:
    serverVersion: "4.0.3"
    superuserSecretRef:
      name: k8ssandra-superuser
    datacenters:
      - metadata:
          name: dc1
        size: {{ .Values.cassandra.datacenterSize }}
        storageConfig:
          cassandraDataVolumeClaimSpec:
  {{- if .Values.rook.enabled }}
            storageClassName: rook-ceph-block-waitforfirstconsumer
  {{- else }}
            storageClassName: standard
  {{- end }}
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
        config:
          jvmOptions:
            heapSize: 1024M
    telemetry:
      prometheus:
        enabled: true