resources:
- keycloak.org_keycloakbackups_crd.yaml
- keycloak.org_keycloakclients_crd.yaml
- keycloak.org_keycloakrealms_crd.yaml
- keycloak.org_keycloaks_crd.yaml
- keycloak.org_keycloakusers_crd.yaml