apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-eventing-kafka-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "7"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: knative-eventing
    server: {{ .Values.spec.destination.server }}
  project: greenlight-project
  source:
    path: base/knative/knative-eventing-kafka-controller
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
