apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: postgres-operator-ui-virtualservice
  namespace: default
  labels:
    name: "postgres-operator-ui"
    team: "acid"
spec:
  gateways:
  - istio-system/istio-gateway
  hosts:
  - postgres.{{ .Values.domainName }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: postgres-operator-ui