apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: helloworld-build-pipeline
spec:
  params:
    - name: git-url
    - name: git-revision
    - name: image-name
    - name: path-to-image-context
      default: /workspace/git-source
  workspaces:
    - name: git-source
  tasks:
    - name: build-docker-image
      taskRef:
        name: build-docker-image
      params:
        - name: pathToContext
        - value: /workspace/source-repo
      resources:
        inputs:
          - name: source-repo
            resource: source-repo
        outputs:
          - name: builtImage
            resource: image-source