apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: helloworld-build-pipeline
spec:
  params:
    - name: git-url
    - name: git-revision
    - name: image-name
    - name: path-to-image-context
      default: /workspace/git-source
  workspaces:
    - name: git-source
  tasks:
    - name: clone-git-repo
      taskRef: git-clone
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
      workspaces:
        - name: output
          workspace: git-source
