apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: helloworld-build-pipeline
spec:
  params:
    - name: git-url
    - name: git-revision
    - name: image-name
  workspaces:
    - name: git-source
  tasks:
    - name: clone-git-repo
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
      workspaces:
        - name: output
          workspace: git-source
    - name: node-build
      taskRef:
        name: node-build
      workspaces:
        - name: output
          workspace: git-source
    - name: build-and-push-image
      taskRef:
        name: kaniko
      params:
        - name: IMAGE
          value: $(params.image-name)
      workspaces:
        - name: source
          workspace: git-source
