apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: k8s.gcr.io/external-dns/external-dns:v0.12.0
        args:
        - --source=ingress
        - --source=service
        - --domain-filter={{ .Values.domainName }}
        - --provider={{ .Values.provider }}
        - --registry=txt
        - --txt-owner-id=greenlight-external-dns-identifier
{{- if eq .Values.provider "linode" }}
        env:
          - name: LINODE_TOKEN
            valueFrom:
              secretKeyRef:
                name: linode-token
                key: token
{{- else if eq .Values.provider "digitalocean" }}
        env:
          - name: DO_TOKEN
            valueFrom:
              secretKeyRef:
                name: digitalocean-token
                key: token
{{- end }}