apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
{{- if eq .Values.provider "google" }}
  annotations:
    iam.gke.io/gcp-service-account: dns-admin@{{ .Values.googleProjectId }}.iam.gserviceaccount.com
{{- end }}