apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: apply-manifest
spec:
  description: >-
    Applies a Kubernetes manifest
  params:
    - name: manifest-path
      description: The path to the manifest in the current source code repository.
      type: string
    - name: kubectl-image
      default: gcr.io/cloud-builders/kubectl@sha256:253bbf752b78f904c1c9e9faed77526532f9d177ba9e50ca7d03cd1cfba6996f #image is huge
      description: Kubectl wrapper image
  workspaces:
    - name: source
  steps:
    - name: apply-manifest
      workingDir: $(workspaces.source.path)
      image: $(params.kubectl-image)
      script: |
        #!/usr/bin/env bash

        kubectl apply -f $(params.manifest-path)