apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: apply-manifest
spec:
  description: >-
    Applies a Kubernetes manifest
  params:
    - name: manifest-path
      description: The path to the manifest in the current source code repository.
      type: string
    - name: kubectl-image
      default: gcr.io/cloud-builders/kubectl@sha256:d8048f6806a3d5808e0c721852aa2448b609597d853a3418ca5d7af92ee30fe9 #image is huge
      description: Kubectl wrapper image
  workspaces:
    - name: source
  steps:
    - name: apply-manifest
      workingDir: $(workspaces.source.path)
      image: $(params.kubectl-image)
      script: |
        #!/usr/bin/env bash

        kubectl apply -f $(params.manifest-path)