apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-preview-chart
spec:
  description: >-
    Deploys a preview Helm chart for a service for isolated integration testing.
  params:
    - name: project-name
      description: The project name for the application to install (should match GitHub repo and Docker image name)
      type: string
    - name: namespace
      description: The namespace to install the preview into
      type: string
    - name: image-tag
      description: The version of the image to deploy and test
      type: string
    - name: image-digest
      description: The digest of the image to deploy and test
      type: string
    - name: helm-image
      default: greenlightcoop/node-utils:0.1.20@sha256:f808007519871240ba6ffc587c8a86b8c657b24c843b6ec9fa99784b86b61236
      description: Helm image
    - name: kubectl-image
      default: gcr.io/cloud-builders/kubectl@sha256:ca8521c92c9b347b8745c4603d395edbf102a6b4015f7adff775639110f308e0 #image is huge
      description: Kubectl wrapper image
  workspaces:
    - name: source
  steps:
    - name: deploy-preview-chart
      workingDir: $(workspaces.source.path)
      image: $(params.helm-image)
      script: |
        #!/usr/bin/env bash
        set -xe

        export CHART_NAME=$(yq '.name' $(workspaces.source.path)/charts/preview/Chart.yaml)

        mkdir -p $(workspaces.source.path)/charts/preview/charts
        cp -r $(workspaces.source.path)/charts/main $(workspaces.source.path)/charts/preview/charts
        helm dependency update ./charts/preview
        helm upgrade --debug --install \
          --namespace $(params.namespace) \
          --set global.debug=true \
          --set global.domain={{ .Values.domainName }} \
          --set global.subdomain=$(params.namespace) \
          --set $(params.project-name).image.tag=$(params.image-tag) \
          --set $(params.project-name).image.digest=$(params.image-digest) \
          $CHART_NAME ./charts/preview
    - name: wait-until-ready
      workingDir: $(workspaces.source.path)
      image: $(params.kubectl-image)
      script: |
        #!/usr/bin/env bash
        set -xe

        kubectl wait -n $(params.namespace) --for=condition=Ready --timeout=240s ksvc/preview-$(params.project-name)
