apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-preview-application
spec:
  description: >-
    Deploys a preview version of a service for isolated integration testing. Based on tekton-catalog kuberenetes-actions
    task. Expects a Kustomize application in the source subdirctory "preview". Makes a copy of the preview manifests
    replacing any instance of ${IMAGE_TAG} with the value passed for the parameter image-version.
  params:
    - name: project-name
      description: The project name for the application to install (should match GitHub repo and Docker image name)
      type: string
    - name: namespace
      description: The namespace to install the preview into
      type: string
    - name: helm-chart-version
      description: The preview Helm chart version to deploy
      type: string
    - name: helm-image
      default: greenlightcoop/node-utils:0.1.20@sha256:f808007519871240ba6ffc587c8a86b8c657b24c843b6ec9fa99784b86b61236
      description: Helm image
  workspaces:
    - name: source
    - name: helm
  steps:
    - name: deploy-preview-application
      workingDir: $(workspaces.source.path)
      image: $(params.helm-image)
      script: |
        #!/usr/bin/env bash
        set -xe

        export CHART_NAME=$(yq '.name' $(workspaces.source.path)/chart/Chart.yaml)

        helm install -n $(params.namespace) \
          --set debug=true,domainName={{ .Values.domainName }},subdomain=$(params.namespace) \
          $CHART_NAME ./chart

        kubectl wait -n $(params.namespace) --for=condition=Ready --timeout=240s ksvc/$(params.project-name)
