apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ensure-namespace-exists
spec:
  description: >-
    Creates a namespace if it doesn't already exists. New namespaces will be labeled with "istio-injection: enabled".
  params:
    - name: namespace
      description: The namespace to create if necessary.
      type: string
    - name: kubectl-image
      default: gcr.io/cloud-builders/kubectl@sha256:253bbf752b78f904c1c9e9faed77526532f9d177ba9e50ca7d03cd1cfba6996f #image is huge
      description: Kubectl wrapper image
  steps:
    - name: ensure-namespace-exists
      image: $(params.kubectl-image)
      script: |
        #!/usr/bin/env bash
        set -ex

        cat <<EOF | kubectl apply -f -
        apiVersion: v1
        kind: Namespace
        metadata:
          name: $(params.namespace)
          labels:
            greenlightcoop.dev/k8ssandra: enabled
            istio-injection: enabled
        EOF