apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: generate-npmrc
spec:
  description: >-
    Adds a .npmrc file with the GitHub token to the checked out workspace.
  workspaces:
    - name: source
  steps:
    - name: set-status
      env:
        - name: GITHUBTOKEN
          valueFrom:
            secretKeyRef:
              name: $(params.GITHUB_TOKEN_SECRET_NAME)
              key: $(params.GITHUB_TOKEN_SECRET_KEY)
      workingDir: $(workspaces.source.path)
      image: busybox:1.34.1@sha256:afcc7f1ac1b49db317a7196c902e61c6c3c4607d63599ee1a82d702d249a0ccb
      script: |
        #!/bin/sh

        set -e
        set -x

        echo "//npm.pkg.github.com/:_authToken$GITHUBTOKEN=" > .npmrc