apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: get-namespace
spec:
  description: >-
    Retrieves the configured destination namespace from an Argo CD application manifest.
  params:
    - name: manifest-path
      description: Retrieve destination namespace from this manifest in the source workspace
    - name: tools-image
      default: greenlightcoop/node-utils:0.1.24@sha256:ba9cf4e4985824c39ef671fcd04c7413391dd12b81320a99906d5ac737a42e5a
      description: Image with yq installed
  workspaces:
    - name: source
  results:
    - name: value
      description: the destination namespace value
  steps:
    - name: get-namespace
      workingDir: $(workspaces.source.path)
      image: $(params.tools-image)
      script: |
        #!/usr/bin/env bash
        set -xe

        NAMESPACE=$(yq '.spec.destination.namespace' $(workspaces.source.path)/$(params.manifest-path))
        echo -n $NAMESPACE > $(results.value.path)