apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: has-file
spec:
  description: >-
    Detemines whether a project contains a specified file.
  params:
    - name: file-path
      description: Path to the file to check for
  workspaces:
    - name: source
  results:
    - name: value
      description: whether the current project source has the given file; result values are either "true" or "false"
  steps:
    - name: has-file
      workingDir: $(workspaces.source.path)
      image: greenlightcoop/node-utils:0.1.23@sha256:7a2904768b6adffffd4ee43344a84cef10d7f548bc5cccf245abc4c925a2d09f
      script: |
        #!/usr/bin/env bash
        set -xe

        export FILE_PATH=$(workspaces.source.path)/$(params.file-path)

        if [ -f "$FILE_PATH" ] 
        then
          echo -n true > $(results.value.path)
        else
          echo -n false > $(results.value.path)
        fi
