apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: helm-lint
  namespace: greenlight-pipelines
spec:
  description: >-
    Checks a Helm chart for correctness.
  params:
    - name: helm-image
      description: Base Node.js image to use for the build
      default: greenlightcoop/node-utils:0.1.21@sha256:f5b7763500c7eddb28de1b82af072c97699604f9bf46e7b4604953e1f0bb6164
  workspaces:
    - name: source
  steps:
    - name: helm-lint
      workingDir: $(workspaces.source.path)
      image: $(params.helm-image)
      script: |
        #!/usr/bin/env bash
        set -ex
 
        if [ -f "./Chart.yaml" ] 
        then
          export HELM_PACKAGE_PATH=.
        elif [ -f "./charts/main/Chart.yaml" ]
        then
          export HELM_PACKAGE_PATH=./charts/main
        elif [ -f "./packages/service/charts/main/Chart.yaml" ]
        then
          export HELM_PACKAGE_PATH=./packages/service/charts/main
        else
          echo 'No Helm chart found'
          exit 1
        fi

        helm dependency update $HELM_PACKAGE_PATH --debug
        helm lint $HELM_PACKAGE_PATH --debug
