apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: parse-templates
spec:
  description: >-
    Recursively process an input directory of files performing Go template parsing, writing output files to an output directory.
  params:
    - name: values
      description: YAML string of values to used for template substitution.
      type: string
  workspaces:
    - name: template-directory
  steps:
    - name: parse-templates
      image: greenlightcoop/template-processor:0.1.8@sha256:40225ed906b03c98999c689be307da55d3ce7845ba47bf7b2dbda1f2e9cb192f
      workingDir: /usr/src/app
      env:
        - name: TEMPLATE_DIRECTORY
          value: $(workspaces.template-directory.path)
        - name: VALUES
          value: $(params.values)
      script: |
        #!/usr/bin/env bash
        set -ex
        dumb-init node dist/index.js