apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: parse-templates
spec:
  description: >-
    Recursively process an input directory of files performing Go template parsing, writing output files to an output directory.
  params:
    - name: values
      description: YAML string of values to used for template substitution.
      type: string
  workspaces:
    - name: template-directory
  steps:
    - name: parse-templates
      image: greenlightcoop/template-processor:0.1.10@sha256:c1915cbecfde4be7f3356b75f8a730b4967d5c7f7ebc85d67b6968c9677b7d01
      workingDir: /usr/src/app
      env:
        - name: TEMPLATE_DIRECTORY
          value: $(workspaces.template-directory.path)
        - name: VALUES
          value: $(params.values)
      script: |
        #!/usr/bin/env bash
        set -ex
        dumb-init node dist/index.js