apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: publish-node-package
  namespace: greenlight-pipelines
spec:
  description: >-
    Publishes a node package version to GitHub.
  params:
    - name: node-image
      description: Base Node.js image to use for the build
      default: greenlightcoop/node-utils:0.1.27@sha256:3fa9d0a4862816e9e820060396899a6de1142a6a90450c3c88b0e81af0890ad4
    - name: subdirectory
      description: Subdirectory within source workspace to build and publish
      default: "."
  workspaces:
    - name: source
  steps:
    - name: publish-node-package
      workingDir: $(workspaces.source.path)/$(params.subdirectory)
      image: $(params.node-image)
      script: |
        #!/usr/bin/env bash
        set -ex
        
        npm run build:clean
        npm publish