apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: publish-node-package
  namespace: greenlight-pipelines
spec:
  description: >-
    Publishes a node package version to GitHub.
  params:
    - name: node-image
      description: Base Node.js image to use for the build
      default: greenlightcoop/node-utils:0.1.24@sha256:ba9cf4e4985824c39ef671fcd04c7413391dd12b81320a99906d5ac737a42e5a
    - name: subdirectory
      description: Subdirectory within source workspace to build and publish
      default: "."
  workspaces:
    - name: source
  steps:
    - name: publish-node-package
      workingDir: $(workspaces.source.path)/$(params.subdirectory)
      image: $(params.node-image)
      script: |
        #!/usr/bin/env bash
        set -ex
        
        npm run build:clean
        npm publish