apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: qc-node-package
  namespace: greenlight-pipelines
spec:
  description: >-
    Runs quality control checks (tests, static analysis, etc.) on a Node.js package.
  params:
    - name: node-image
      description: Base Node.js image to use for the build
      default: greenlightcoop/node-utils:0.1.17@sha256:1ca2c1abf6d1e3ce74184485856abc3bde47b9fa24f6ebd3df4fc344934b6602
  workspaces:
    - name: source
  steps:
    - name: qc-node-package
      workingDir: $(workspaces.source.path)
      image: $(params.node-image)
      script: |
        #!/usr/bin/env bash
        set -ex
        
        # Check codebase and build
        npm ci
        npm run qc
