apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: qc-node-package
  namespace: greenlight-pipelines
spec:
  description: >-
    Runs quality control checks (tests, static analysis, etc.) on a Node.js package.
  params:
    - name: node-image
      description: Base Node.js image to use for the build
      default: greenlightcoop/node-utils:0.1.24@sha256:ba9cf4e4985824c39ef671fcd04c7413391dd12b81320a99906d5ac737a42e5a
    - name: subdirectory
      description: Subdirectory within source workspace containing Node project to QC
      default: "."
  workspaces:
    - name: source
  steps:
    - name: qc-node-package
      workingDir: $(workspaces.source.path)/$(params.subdirectory)
      image: $(params.node-image)
      script: |
        #!/usr/bin/env bash
        set -ex
        
        # Check codebase and build
        npm ci
        npm run qc
