apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: qc-node-package
  namespace: greenlight-pipelines
spec:
  description: >-
    Runs quality control checks (tests, static analysis, etc.) on a Node.js package.
  params:
    - name: node-image
      description: Base Node.js image to use for the build
      default: greenlightcoop/node-utils:0.1.28@sha256:8d89e9c6b445581374b26e7bc31443e62cf0960e2f0c22ada49238bdd6bb2317
    - name: subdirectory
      description: Subdirectory within source workspace containing Node project to QC
      default: "."
  workspaces:
    - name: source
  steps:
    - name: qc-node-package
      workingDir: $(workspaces.source.path)/$(params.subdirectory)
      image: $(params.node-image)
      script: |
        #!/usr/bin/env bash
        set -ex
        
        # Check codebase and build
        npm ci
        npm run qc
