apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-npm-scripts
  namespace: greenlight-pipelines
spec:
  description: >-
    Runs one or more NPM scripts in a Node project.
  params:
    - name: node-image
      description: Base Node.js image to use for the build
      default: greenlightcoop/node-utils:0.1.21@sha256:f5b7763500c7eddb28de1b82af072c97699604f9bf46e7b4604953e1f0bb6164
    - name: scripts
      description: npm scripts in project package.json to execute
      type: array
    - name: subdirectory
      description: Subdirectory within source workspace containing Node project to QC
      default: "."
  workspaces:
    - name: source
  steps:
    - name: run-npm-scripts
      workingDir: $(workspaces.source.path)/$(params.subdirectory)
      image: $(params.node-image)
      args: ["$(params.scripts[*])"]
      script: |
        #!/usr/bin/env bash
        set -ex

        for script in "$@" 
        do
          npm run $script
        done
