apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-npm-commands
  namespace: greenlight-pipelines
spec:
  description: >-
    Runs one or more NPM commands in a Node project.
  params:
    - name: node-image
      description: Base Node.js image to use for the build
      default: greenlightcoop/node-utils:0.1.28@sha256:8d89e9c6b445581374b26e7bc31443e62cf0960e2f0c22ada49238bdd6bb2317
    - name: commands
      description: npm commands in project package.json to execute
      type: array
    - name: subdirectory
      description: Subdirectory within source workspace containing Node project to QC
      default: "."
    - name: fail-on-error
      description: If any of the npm commands fail exit with a non-zero status failing the build
      default: "true"
  workspaces:
    - name: source
  steps:
    - name: run-npm-commands
      workingDir: $(workspaces.source.path)/$(params.subdirectory)
      image: $(params.node-image)
      args: ["$(params.commands[*])"]
      script: |
        #!/usr/bin/env bash

        FAIL_ON_ERROR=$(params.fail-on-error)
        if [ "${FAIL_ON_ERROR,,}" = "true" ]; then
          set -ex
        else
          set -x
        fi

        for command in "$@" 
        do
          npm $command
        done
        if [ "${FAIL_ON_ERROR,,}" != "true" ]; then
          exit 0
        fi
