apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: snyk-container-test
spec:
  description: >-
    Runs snyk container test on workspace Dockerfile. Task fails if there's a vulnerability found with an available 
    remediation.
  params:
    - name: image
      description: Tag of image in Docker Hub to assess.
      type: string
  workspaces:
    - name: source
  steps:
    - name: snyk-container-test
      image: greenlightcoop/snyk-tools:0.1.2@sha256:02acc4110fa0415738679c760073000004252b0e21a7b91dec9653961113a522
      workingDir: $(workspaces.source.path)
      env:
        - name: SNYK_TOKEN
          valueFrom:
            secretKeyRef:
              name: snyk
              key: token
      script: |
        #!/usr/bin/env bash
        set -ex
        snyk config set org=greenlight
        snyk config set disableSuggestions=true
        snyk container test --fail-on=all $(params.image) --file=$(workspaces.source.path)/Dockerfile
