apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: snyk-test
spec:
  description: >-
    Runs various snyk tools (test, scan) on workspace resources. Task fails if there's a
    vulnerability found with an available remediation.
  workspaces:
    - name: source
  steps:
    - name: apply-snyk-tests
      image: greenlightcoop/snyk-tools:0.1.7@sha256:15a6ac5efd820f85485c2b56b8b512e2d7916df682cd88bd76806b0441bf0f04
      workingDir: $(workspaces.source.path)
      env:
        - name: SNYK_TOKEN
          valueFrom:
            secretKeyRef:
              name: snyk
              key: token
      script: |
        #!/usr/bin/env bash
        set -x

        snyk config set org=greenlight
        snyk config set disableSuggestions=true
        
        npm run snyk:test
        exit 0
