apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: snyk-test
spec:
  description: >-
    Runs various snyk tools (test, scan) on workspace resources. Task fails if there's a
    vulnerability found with an available remediation.
  workspaces:
    - name: source
  steps:
    - name: apply-snyk-tests
      image: greenlightcoop/snyk-tools:0.1.5@sha256:d88b253f337761b08b52758154a07469b5976371bae5a0b2811e3df63074f786
      workingDir: $(workspaces.source.path)
      env:
        - name: SNYK_TOKEN
          valueFrom:
            secretKeyRef:
              name: snyk
              key: token
      script: |
        #!/usr/bin/env bash
        set -ex
        snyk config set org=greenlight
        snyk config set disableSuggestions=true
        if [ -d "$(workspaces.source.path)/src" ] 
        then
          snyk code test --fail-on=all || echo 'snyk code test identified potential issues'
        else
          echo 'No src directory, skipping snyk code test'
        fi
        if [ -f "$(workspaces.source.path)/package.json" ] 
        then
          snyk test --fail-on=all
        else
          echo 'No package.json, skipping snyk test'
        fi
