apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: snyk-monitor
spec:
  description: >-
    Sets up Snyk monitoring on project assets.
  params:
    - name: image
      description: Tag of image in Docker Hub to assess.
      type: string
      default: ""
  workspaces:
    - name: source
  steps:
    - name: snyk-monitor
      image: greenlightcoop/snyk-tools:0.1.5@sha256:d88b253f337761b08b52758154a07469b5976371bae5a0b2811e3df63074f786
      workingDir: $(workspaces.source.path)
      env:
        - name: SNYK_TOKEN
          valueFrom:
            secretKeyRef:
              name: snyk
              key: token
      script: |
        #!/usr/bin/env bash
        set -x
        snyk config set org=greenlight
        snyk config set disableSuggestions=true
        if [ -f "$(workspaces.source.path)/package.json" ] 
        then
          snyk monitor
        else
          echo 'No package.json, skipping snyk monitor'
        fi
        if [ -f "$(workspaces.source.path)/Dockerfile" ] 
        then
          snyk container monitor $(params.image) --file=$(workspaces.source.path)/Dockerfile
        else
          echo 'No Dockerfile, skipping snyk container monitor'
        fi
        exit 0
