apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: uninstall-helm-chart
spec:
  description: >-
    Removes a previously deployed Helm chart.
  params:
    - name: namespace
      description: The namespace to remove the preview chart from
      type: string
    - name: release-name
      description: The helm release to uninstall
      type: string
    - name: helm-image
      default: greenlightcoop/node-utils:0.1.27@sha256:3fa9d0a4862816e9e820060396899a6de1142a6a90450c3c88b0e81af0890ad4
      description: Helm image
  steps:
    - name: uninstall-helm-chart
      image: $(params.helm-image)
      script: |
        #!/usr/bin/env bash
        set -xe

        if helm status --namespace $(params.namespace) $(params.release-name)
        then
          helm uninstall --debug --namespace $(params.namespace) $(params.release-name)
        fi