apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: uninstall-helm-chart
spec:
  description: >-
    Removes a previously deployed Helm chart.
  params:
    - name: namespace
      description: The namespace to remove the preview chart from
      type: string
    - name: release-name
      description: The helm release to uninstall
      type: string
    - name: helm-image
      default: greenlightcoop/node-utils:0.1.26@sha256:7194d4351cbfa64bc4e6f9789a20e20ad8cbb6bc29c78bf921400a1497155d1f
      description: Helm image
  steps:
    - name: uninstall-helm-chart
      image: $(params.helm-image)
      script: |
        #!/usr/bin/env bash
        set -xe

        if helm status --namespace $(params.namespace) $(params.release-name)
        then
          helm uninstall --debug --namespace $(params.namespace) $(params.release-name)
        fi