apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: uninstall-helm-chart
spec:
  description: >-
    Removes a previously deployed Helm chart.
  params:
    - name: namespace
      description: The namespace to remove the preview chart from
      type: string
    - name: release-name
      description: The helm release to uninstall
      type: string
    - name: helm-image
      default: greenlightcoop/node-utils:0.1.25@sha256:ac291a4a1346e3e5938cf89818a71e093c05cd94e00f3ee49bbd5aa2fa985b77
      description: Helm image
  steps:
    - name: uninstall-helm-chart
      image: $(params.helm-image)
      script: |
        #!/usr/bin/env bash
        set -xe

        if helm status --namespace $(params.namespace) $(params.release-name)
        then
          helm uninstall --debug --namespace $(params.namespace) $(params.release-name)
        fi