apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: uninstall-helm-chart
spec:
  description: >-
    Removes a previously deployed Helm chart.
  params:
    - name: namespace
      description: The namespace to remove the preview chart from
      type: string
    - name: release-name
      description: The helm release to uninstall
      type: string
    - name: helm-image
      default: greenlightcoop/node-utils:0.1.28@sha256:8d89e9c6b445581374b26e7bc31443e62cf0960e2f0c22ada49238bdd6bb2317
      description: Helm image
  steps:
    - name: uninstall-helm-chart
      image: $(params.helm-image)
      script: |
        #!/usr/bin/env bash
        set -xe

        if helm status --namespace $(params.namespace) $(params.release-name)
        then
          helm uninstall --debug --namespace $(params.namespace) $(params.release-name)
        fi