apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: wait-for-stage-ready
spec:
  description: >-
    Waits for deployment to a stage to complete.
  params:
    - name: namespace
      description: The namespace the stage is deployed in.
      type: string
    - name: kubectl-image
      default: gcr.io/cloud-builders/kubectl@sha256:57df6708b97ea047bfbb285ee872a4e2785cfb1ce958d40240d851bb077d7c43 #image is huge
      description: Kubectl wrapper image
  steps:
    - name: wait-for-stage-ready
      image: $(params.kubectl-image)
      script: |
        #!/usr/bin/env bash
        set -ex

        while : ; do
          COUNT=$(kubectl -n $(params.namespace) get services.serving.knative.dev -o jsonpath='{.items[*].metadata.name}' | wc -w)
          if [ "$COUNT" -gt "0" ]; then break; fi
          sleep 5
        done

        for ksvc in `kubectl -n $(params.namespace) get services.serving.knative.dev -o jsonpath='{.items[*].metadata.name}'`
        do 
          kubectl wait -n $(params.namespace) --for=condition=Ready --timeout=240s ksvc/$ksvc
        done