apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: yq
spec:
  description: >-
    Get the results of a yq YAML query.
  params:
    - name: query
      description: yq query
    - name: yaml-path
      description: Retrieve results from this YAML file in the source workspace
    - name: tools-image
      default: greenlightcoop/node-utils:0.1.27@sha256:3fa9d0a4862816e9e820060396899a6de1142a6a90450c3c88b0e81af0890ad4
      description: Image with yq installed
  workspaces:
    - name: source
  results:
    - name: value
      description: the yq query results
  steps:
    - name: yq
      workingDir: $(workspaces.source.path)
      image: $(params.tools-image)
      script: |
        #!/usr/bin/env bash
        set -xe

        RESULT=$(yq '$(params.query)' $(workspaces.source.path)/$(params.yaml-path))
        echo -n $RESULT > $(results.value.path)