apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: yq
spec:
  description: >-
    Get the results of a yq YAML query.
  params:
    - name: query
      description: yq query
    - name: yaml-path
      description: Retrieve results from this YAML file in the source workspace
    - name: tools-image
      default: greenlightcoop/node-utils:0.1.28@sha256:8d89e9c6b445581374b26e7bc31443e62cf0960e2f0c22ada49238bdd6bb2317
      description: Image with yq installed
  workspaces:
    - name: source
  results:
    - name: value
      description: the yq query results
  steps:
    - name: yq
      workingDir: $(workspaces.source.path)
      image: $(params.tools-image)
      script: |
        #!/usr/bin/env bash
        set -xe

        RESULT=$(yq '$(params.query)' $(workspaces.source.path)/$(params.yaml-path))
        echo -n $RESULT > $(results.value.path)